--BULK INSERT WorldCupSchema.Players
--FROM 'C:\Users\rob\source\repos\FifaDatabase\scraped_webdata\GetSoccerStats\players.csv'
--WITH
--(
--    FIRSTROW = 1,
--    FIELDTERMINATOR = ',',  --CSV field delimiter
--    ROWTERMINATOR = '\n',   --Use to shift the control to next row
--    TABLOCK
--)
--GO
--DELETE FROM WorldCupSchema.Players WHERE 1 != 2;
SELECT * FROM WorldCupSchema.Players;